version: 2

models:
  - name: stg_yield_raw_data
    description: "Yield Raw Data with season and production system"
    columns:
      - name: yield_raw_data_sk
        description: "Surrogate key over business grain"
        tests:
          - not_null
      - name: country
        tests:
          - not_null
      - name: product
        tests:
          - not_null
      - name: yield
        tests:
          - not_null
      - name: source_natural_key
        tests:
          - not_null
          - accepted_values:
              values:
                - 'yield_raw_data'
      - name: loaded_at
        tests:
          - not_null

    tests:
      - dbt_utils.recency:
          datepart: day
          field: loaded_at
          interval: 14

  - name: stg_ilri_dairy_genetics
    description: "ILRI Dairy Genetics East Africa - Milk yields + Calving records"
    columns:
      - name: ilri_dairy_genetics_sk
        description: "Surrogate key over business grain"
        tests:
          - not_null
      - name: client_id
        tests:
          - not_null
      - name: farm_code
        tests:
          - not_null
      - name: cow_number
        tests:
          - not_null
      - name: record_type
        tests:
          - not_null
          - accepted_values:
              values:
                - 'milk'
                - 'calving'
      - name: source_natural_key
        tests:
          - not_null
      - name: loaded_at
        tests:
          - not_null

    tests:
      - dbt_utils.recency:
          datepart: day
          field: loaded_at
          interval: 30
