"""Shared content for RAG pipeline architecture DOCX and PDF generators."""
from __future__ import annotations

from pathlib import Path
from typing import Any, Sequence

ML_ENG_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = ML_ENG_ROOT / "ml" / "rag" / "docs"
DIAGRAMS_DIR = DOCS_DIR / "diagrams"
DIAGRAMS_PNG_DIR = DIAGRAMS_DIR / "png"

OUTPUT_DOCX = DOCS_DIR / "OpenTrace-RAG-Pipeline-Architecture.docx"
OUTPUT_PDF = DOCS_DIR / "OpenTrace-RAG-Pipeline-Architecture.pdf"

DIAGRAM_FILES: Sequence[str] = (
    "system_context.mmd",
    "entry_points.mmd",
    "runtime_graph.mmd",
    "control_plane.mmd",
    "measure_ontology.mmd",
    "corpus_router.mmd",
    "vector_retrieve.mmd",
    "six_corpora.mmd",
    "bq_retrieve_subflow.mmd",
    "merge_rerank.mmd",
    "generate_acf_subflow.mmd",
    "plan_persona.mmd",
    "runtime_erd.mmd",
    "ingest_erd.mmd",
    "infra_erd.mmd",
)

# PDF section order: vector stack before BQ (locked by architecture plan).
DIAGRAM_SECTIONS: Sequence[tuple[str, str, str]] = (
    ("system_context", "System context", "Actors, LangGraph, and external services — Qdrant and BigQuery as peer retrieval backends."),
    ("entry_points", "Entry points", "CLI, FastAPI, Chatbot v1, and Streamlit routes into run_rag / LangGraph."),
    ("runtime_graph", "Full LangGraph (E2E)", "Start-to-finish graph with vector and BQ retrieval legs into merge."),
    ("control_plane", "Control plane", "Enricher → decompose → Africa scope → measure ontology → task_mode → route."),
    ("measure_ontology", "Measure ontology (BQ aid)", "resolve_measure → reasoner_scope → LLM reasoner retries → ontology fallback last resort."),
    ("corpus_router", "Corpus router", "select_corpora gates which of six Qdrant collections to query (max soft-skip 3)."),
    ("vector_retrieve", "Vector retrieve (per-corpus cascade)", "E5 embed → filters → hybrid RRF → filter cascade → vector_*_results."),
    ("six_corpora", "Six Qdrant corpora", "Collections, doc_kind, and RAGGraphState vector_* fields."),
    ("bq_retrieve_subflow", "BigQuery retrieve", "Ontology-scoped reason → templates/NL2SQL → execute → enrich/cache."),
    ("merge_rerank", "Merge and rerank", "Fuse vector chunks + BQ rows; pin BQ for fact/analytical; cross-encoder rerank."),
    ("generate_acf_subflow", "Generation and ACF", "Pack vector+BQ context → persona/recency → LLM → citations → ACF Path B."),
    ("plan_persona", "Plan tiers and personas", "plan_type gates, category personas, investor overlay, recency tiers."),
    ("runtime_erd", "Runtime domain ERD", "Query-time session, state, and generation entities."),
    ("ingest_erd", "Ingest and vector store ERD", "Offline document → chunk → Qdrant pipeline."),
    ("infra_erd", "Infrastructure ERD", "External services invoked by LangGraph."),
)

DOC_VERSION = "2.0"

PURPOSE_BULLETS: Sequence[str] = (
    "Co-equal retrieval: six Qdrant text corpora (unstructured) and BigQuery staging_dev (structured).",
    "Orchestrate via LangGraph in ml/rag/chatbot/graph.py — vector parallel_retrieve then BQ reason/retrieve, both legs merge.",
    "Control plane: query enricher (memory) → decompose → Africa panel/ranking → agri measure ontology → task_mode.",
    "Ontology aids the BQ SQL reasoner (scoped tables/filters); does not replace the LLM; fallback only after retries.",
    "Retrieval uses the latest user message (enriched if elliptical); chat memory affects generation and enricher.",
    "BigQuery SQL is staging_dev-only; validated SELECT with LIMIT; Yield/trade/prices/IPC/soil are not Production-locked.",
    "LLM steps fail soft — empty LLM returns ontology/heuristic fallbacks or context-only answers, not graph crashes.",
    "ACF (ADZA Confidence Framework) scores cited evidence only (Path B, 0–100) from packed vector + BQ sources.",
)

BQ_ENRICH_BULLETS: Sequence[str] = (
    "enrich_bq_results stamps year, as_of_date, metric, unit from SQL/decomposition.",
    "ranked_table consolidation merges multi-row BQ rankings into one context item.",
    "maybe_attach_ranking_trend runs FAOSTAT Production+Yield bracketing years (Y-1 vs Y+1).",
    "Session ranking cache (last_structured_ranking) skips BQ on compatible follow-ups.",
    "context_item_to_acf_record requires as_of_date — ranked_table must be stamped.",
)

ENTRY_POINTS_FLOWCHART: Sequence[str] = (
    "┌─────────────────────────────────────────────────────────────────┐",
    "│                        Entry points                              │",
    "└─────────────────────────────────────────────────────────────────┘",
    "  CLI (ml/rag/run.py)              FastAPI POST /query",
    "         │                                  │",
    "         └──────────────┬───────────────────┘",
    "                        ▼",
    "                   run_rag(query, **kwargs)",
    "                        │",
    "  Chatbot v1 POST /v1/chat          Streamlit QA",
    "         │                                  │",
    "         ▼                                  │",
    "  execute_chat_turn(...) ──────────────────┘",
    "         │",
    "         ▼",
    "  LangGraph compiled graph (chatbot/graph.py)",
)

FULL_GRAPH_FLOWCHART: Sequence[str] = (
    "START",
    "  │",
    "  ▼",
    "decompose (enricher + ontology + task_mode inside node)",
    "  ├─ clarify ────────────────────────────► generate_clarify ──► END",
    "  ├─ is_meta_query ──────────────────────► generate_meta ──────► END",
    "  ├─ is_product_query ───────────────────► generate_product ───► END",
    "  ├─ is_greeting_query OR is_out_of_scope ► generate_social ─────► END",
    "  ├─ is_language_unknown ────────────────► generate_language_help ► END",
    "  │",
    "  └─ full_rag",
    "        │",
    "        ▼",
    "  ┌──── parallel_retrieve (VECTOR LEG) ────┐",
    "  │  select_corpora → up to 6 Qdrant corpora │",
    "  │  E5 / hybrid RRF / filter cascade         │",
    "  │  → vector_*_results                      │",
    "  └──────────────────────────────────────────┘",
    "        │",
    "        ▼",
    "  ┌──── bq_reason → bq_retrieve (BQ LEG) ────┐",
    "  │  ontology-scoped reasoner + retries        │",
    "  │  templates / NL2SQL → staging_dev execute │",
    "  │  → bq_results                             │",
    "  └───────────────────────────────────────────┘",
    "        │",
    "        ▼",
    "  merge (vector + BQ) ──► rerank",
    "        │",
    "        ◆ weak context + web fallback?",
    "        yes ──► web_fallback ──◆ insufficient? yes ► insufficient_context ► END",
    "        │                         no ──────────────────────────────┐",
    "        no (enough / web off) ─────────────────────────────────────┤",
    "                                                                   ▼",
    "                                                             generate ──► export ──► END",
)

NODE_INVENTORY: Sequence[Sequence[str]] = (
    ("START", "bookend", "LangGraph entry; routes to decompose"),
    ("decompose", "routing", "Enricher + decompose + Africa scope + ontology + task_mode; short-circuit routes"),
    ("parallel_retrieve", "pipeline", "VECTOR LEG: corpus router + concurrent Qdrant retrieve (six corpora)"),
    ("bq_reason", "pipeline", "BQ LEG: ontology-scoped table/SQL plan via YAML reasoner + retries"),
    ("bq_retrieve", "pipeline", "BQ LEG: execute SQL, enrich results, ranking cache, trend companion"),
    ("merge", "pipeline", "Fuse vector_* + bq_results into merged_context"),
    ("rerank", "routing", "Cross-encoder rerank; may route to web_fallback or generate"),
    ("web_fallback", "routing", "Wikipedia/Tavily append when context weak"),
    ("insufficient_context", "terminal", "Deterministic gap message when evidence still insufficient"),
    ("generate", "pipeline", "Pack vector+BQ context, persona/recency, LLM, citations, ACF Path B"),
    ("export", "pipeline", "CSV/chart/DOCX/PDF artifacts when export_enabled + intent"),
    ("generate_clarify", "terminal", "Slot-aware clarify (measure-aware); no retrieval"),
    ("generate_meta", "terminal", "Assistant identity / meta answers without retrieval"),
    ("generate_product", "terminal", "Product FAQ answers without retrieval"),
    ("generate_social", "terminal", "Greetings and out-of-scope polite responses"),
    ("generate_language_help", "terminal", "Ask user to rephrase when language unknown"),
    ("END", "bookend", "LangGraph exit after terminal or export node"),
)

ROUTING_TABLE: Sequence[Sequence[str]] = (
    ("After decompose", "task_mode=clarify", "generate_clarify", "Missing slots per measure ontology"),
    ("After decompose", "is_meta_query", "generate_meta", "No retrieval; curated ACF"),
    ("After decompose", "is_product_query", "generate_product", "Product FAQ; curated ACF"),
    ("After decompose", "is_greeting_query OR is_out_of_scope_query", "generate_social", "Social/gate answer"),
    ("After decompose", "is_language_unknown", "generate_language_help", "Language help stub"),
    ("After decompose", "else (full_rag)", "parallel_retrieve", "Vector leg then BQ leg"),
    ("After parallel_retrieve", "always", "bq_reason", "BQ plan (ontology-scoped)"),
    ("After bq_reason", "always", "bq_retrieve", "Execute or skip_bq empty"),
    ("After bq_retrieve", "always", "merge", "Fuse vector + BQ"),
    ("After merge", "always", "rerank", "Score and trim"),
    ("After rerank", "Usable chunks low + web fallback enabled", "web_fallback", "Wikipedia/Tavily append"),
    ("After rerank", "Enough context OR web off", "generate", "LLM generation"),
    ("After web_fallback", "insufficient_context=true", "insufficient_context", "Deterministic gap message"),
    ("After web_fallback", "else", "generate", "Proceed with augmented context"),
    ("After generate", "always", "export", "Artifacts when export_enabled + intent"),
)

RUNTIME_ERD_ENTITIES: Sequence[tuple[str, Sequence[Sequence[str]]]] = (
    (
        "Session",
        (
            ("session_id", "str", "PK"),
            ("conversation_summary", "str|null", ""),
            ("recent_turns", "list|null", ""),
            ("category", "str|null", ""),
            ("plan_type", "str|null", ""),
            ("country", "str|null", ""),
            ("last_structured_ranking", "dict|null", "Ranking cache blob"),
        ),
    ),
    (
        "ChatTurn",
        (
            ("turn_id", "str", "PK"),
            ("session_id", "str", "FK → Session"),
            ("query", "str", ""),
            ("answer", "str", ""),
            ("created_at", "datetime", ""),
        ),
    ),
    (
        "RAGGraphState",
        (
            ("state_id", "str", "PK (implicit per turn)"),
            ("query", "str", ""),
            ("merged_context", "list", ""),
            ("reranked_context", "list", ""),
            ("answer", "str", ""),
            ("citations", "list", ""),
            ("acf_*", "mixed", "ACF signal fields"),
            ("artifacts", "list", ""),
        ),
    ),
        (
            "Decomposition",
            (
                ("intent", "str", ""),
                ("entities", "list", ""),
                ("geography", "list", ""),
                ("domains", "list", ""),
                ("time_start", "str|null", ""),
                ("time_end", "str|null", ""),
                ("africa_default", "bool|null", "Which-country Africa ranking"),
                ("africa_panel", "bool|null", "Full ~54-country panel"),
                ("expanded_regions", "list|null", "Region keys expanded to countries"),
            ),
        ),
    (
        "VectorChunk",
        (
            ("id", "str", "PK"),
            ("corpus", "str", "news|academic|policy|…"),
            ("text", "str", ""),
            ("score", "float", ""),
            ("metadata", "dict", "geo, published_at, doc_kind"),
        ),
    ),
    (
        "BQContextItem",
        (
            ("id", "str", "PK"),
            ("source", "str", "bigquery"),
            ("text", "str", "Row prose or ranked_table summary"),
            ("metadata", "dict", "sql, bq_enrichment, ranked_rows"),
        ),
    ),
    (
        "StructuredRankingCache",
        (
            ("fingerprint", "str", "PK"),
            ("item", "dict", "Cached ranked_rows context item"),
            ("decomposition", "dict", "Matching decomposition snapshot"),
        ),
    ),
    (
        "ContextItem",
        (
            ("id", "str", "PK"),
            ("source", "str", "vector|bigquery|web"),
            ("text", "str", ""),
            ("metadata", "dict", ""),
        ),
    ),
    (
        "GenerationResult",
        (
            ("answer", "str", ""),
            ("citations", "list", ""),
            ("usage", "dict", "LLM tokens"),
            ("langfuse_trace_id", "str|null", ""),
        ),
    ),
    (
        "Citation",
        (
            ("index", "int", "PK"),
            ("source_kind", "str", ""),
            ("title", "str", ""),
            ("url", "str|null", ""),
            ("metadata", "dict", ""),
        ),
    ),
    (
        "ACFSignal",
        (
            ("band", "str", "High|Moderate|Low"),
            ("score", "int|float", "0–100"),
            ("explanation", "str", ""),
            ("components", "dict|null", "T/A/F/G breakdown"),
        ),
    ),
    (
        "Artifact",
        (
            ("artifact_id", "str", "PK"),
            ("kind", "str", "csv|chart|docx|pdf"),
            ("uri", "str", "GCS or local URI"),
            ("label", "str", ""),
        ),
    ),
    (
        "RankedTableMeta",
        (
            ("rank", "int", ""),
            ("entity", "str", "Country/crop name"),
            ("metric_value", "float", ""),
            ("metric", "str", ""),
            ("unit", "str", ""),
            ("year", "int|null", ""),
            ("as_of_date", "str", "Required for ACF"),
        ),
    ),
)

RUNTIME_ERD_RELATIONSHIPS: Sequence[Sequence[str]] = (
    ("Session", "1:N", "ChatTurn", "contains"),
    ("ChatTurn", "1:1", "RAGGraphState", "produces"),
    ("RAGGraphState", "1:1", "Decomposition", "has"),
    ("RAGGraphState", "1:N", "VectorChunk", "vector_*_results"),
    ("RAGGraphState", "1:N", "BQContextItem", "bq_results"),
    ("RAGGraphState", "1:0..1", "StructuredRankingCache", "structured_ranking_cache"),
    ("RAGGraphState", "1:N", "ContextItem", "merged_context / reranked_context"),
    ("RAGGraphState", "1:1", "GenerationResult", "answer_citations_acf"),
    ("GenerationResult", "1:N", "Citation", "citations"),
    ("GenerationResult", "1:1", "ACFSignal", "acf"),
    ("GenerationResult", "0:N", "Artifact", "artifacts"),
    ("BQContextItem", "0:N", "RankedTableMeta", "ranked_rows"),
)

INGEST_ERD_ENTITIES: Sequence[tuple[str, Sequence[Sequence[str]]]] = (
    (
        "SourceDocument",
        (
            ("document_id", "str", "PK"),
            ("doc_kind", "str", "news_article|academic_article|…"),
            ("content_hash", "str", "SHA for incremental skip"),
            ("source_uri", "str|null", "Drive path or file path"),
        ),
    ),
    (
        "Chunk",
        (
            ("id", "UUID5", "PK"),
            ("document_id", "str", "FK → SourceDocument"),
            ("text", "str", ""),
            ("chunk_index", "int", ""),
            ("metadata", "dict", "geo, dates, lanes"),
        ),
    ),
    (
        "QdrantPoint",
        (
            ("id", "UUID5", "PK (= Chunk.id)"),
            ("dense_vector", "float[]", ""),
            ("sparse_vector", "dict|null", "BM25 sparse when hybrid"),
            ("payload", "dict", "doc_kind, country, published_at, …"),
        ),
    ),
    (
        "QdrantCollection",
        (
            ("name", "str", "PK"),
            ("corpus_key", "str", "news|academic_papers|…"),
            ("vector_dims", "int", ""),
            ("payload_indexes", "list", "geo, dates, doc_kind"),
        ),
    ),
    (
        "IngestManifest",
        (
            ("document_id", "str", "PK/FK"),
            ("content_hash", "str", ""),
            ("ingested_at", "datetime", ""),
            ("ingest_version", "str", "Bump to force rebuild"),
        ),
    ),
)

INGEST_ERD_RELATIONSHIPS: Sequence[Sequence[str]] = (
    ("SourceDocument", "1:N", "Chunk", "chunked_into"),
    ("Chunk", "1:1", "QdrantPoint", "upserted_as"),
    ("QdrantCollection", "1:N", "QdrantPoint", "stores"),
    ("IngestManifest", "1:1", "SourceDocument", "tracks"),
)

INFRA_ERD_ENTITIES: Sequence[tuple[str, Sequence[Sequence[str]]]] = (
    (
        "FastAPI",
        (
            ("service", "str", "RAG API / Chatbot v1 / Streamlit"),
            ("endpoint", "str", "POST /query, /v1/chat, …"),
        ),
    ),
    (
        "LangGraph",
        (
            ("module", "str", "chatbot/graph.py"),
            ("nodes", "16", "decompose … export + terminals"),
        ),
    ),
    (
        "Redis",
        (
            ("key_prefix", "str", "rag:session:*"),
            ("ttl_seconds", "int", "RAG_SESSION_TTL_SECONDS"),
            ("also", "str", "BQ schema cache"),
        ),
    ),
    (
        "Qdrant",
        (
            ("url", "str", "QDRANT_URL"),
            ("collections", "6", "news, academic, policy, …"),
            ("mode", "str", "hybrid dense+sparse (optional)"),
        ),
    ),
    (
        "BigQuery",
        (
            ("project", "str", "BQ_PROJECT"),
            ("dataset", "str", "staging_dev (BQ_DATASET_SILVER)"),
        ),
    ),
    (
        "LLMProvider",
        (
            ("base_url", "str", "RAG_LLM_BASE_URL"),
            ("model", "str", "RAG_LLM_MODEL_ID"),
            ("uses", "str", "decompose, NL2SQL, generate, …"),
        ),
    ),
    (
        "Langfuse",
        (
            ("traces", "bool", "Optional observed spans per node"),
            ("feedback", "bool", "POST /feedback scores"),
        ),
    ),
    (
        "BQRetriever",
        (
            ("module", "str", "bq_retriever.py"),
            ("modes", "str", "templates + NL2SQL per_hint|batch"),
        ),
    ),
)

INFRA_ERD_RELATIONSHIPS: Sequence[Sequence[str]] = (
    ("FastAPI", "1:1", "LangGraph", "invokes"),
    ("LangGraph", "1:N", "Redis", "session_blob"),
    ("LangGraph", "1:N", "Qdrant", "vector_search"),
    ("LangGraph", "1:N", "BigQuery", "sql_execute"),
    ("LangGraph", "1:N", "LLMProvider", "decompose_reason_nl2sql_generate"),
    ("LangGraph", "0:1", "Langfuse", "traces"),
    ("BQRetriever", "1:1", "BigQuery", "schema_cache"),
)

BQ_SUBFLOW_CHART: Sequence[str] = (
    "node_bq_retrieve",
    "  │",
    "  ▼",
    "  ◆ ranking follow-up?",
    "  (structured_ranking_cache + is_ranking_follow_up)",
    "  │",
    "  ├─ yes ──► reuse ranked_rows (bq_cache_hit=true) ──► merge",
    "  │",
    "  └─ no",
    "        │",
    "        ▼",
    "  BQRetriever.retrieve",
    "        │",
    "        ├─ SQL templates (faostat_country_rank, price rank, …)",
    "        ├─ NL2SQL LLM (per_hint or batch)",
    "        ├─ bq_sql_validate (SELECT-only, staging_dev allowlist)",
    "        └─ BigQuery execute",
    "        │",
    "        ▼",
    "  enrich_bq_results",
    "        ├─ resolve_row_semantics + format_row_prose",
    "        ├─ consolidate ranked_table (ranking queries)",
    "        ├─ _stamp_acf_metadata (year, as_of_date, metric, geo)",
    "        └─ maybe_attach_ranking_trend (Production+Yield Y-1 vs Y+1)",
    "        │",
    "        ▼",
    "  trim_bq_result_contents (byte budget)",
    "        │",
    "        ▼",
    "  cache_entry_from_bq_results → structured_ranking_cache",
    "        │",
    "        ▼",
    "      merge",
)

ACF_SUBFLOW_CHART: Sequence[str] = (
    "generate (generator.py + acf_scoring.py + acf_metadata.py)",
    "  │",
    "  ▼",
    "  pack context as [Source N | kind | detail]",
    "  │",
    "  ▼",
    "  LLM answer with inline [N] footnotes",
    "  │",
    "  ▼",
    "  _strip_invalid_citation_markers (remove [N] not in registry)",
    "  │",
    "  ▼",
    "  referenced_citations (RAG_CITATIONS_MODE=referenced default)",
    "  │",
    "  ▼",
    "  score_cited_evidence (ACF Path B on cited refs only)",
    "        │",
    "        ├─ context_item_to_acf_record (requires as_of_date)",
    "        ├─ adapt_cited_claims → score_evidence",
    "        └─ acf_signal_from_result → API acf object",
)

RAG_STATE_FIELDS: Sequence[Sequence[str]] = (
    ("query", "str", "Working question (may be enriched from memory)"),
    ("enriched_query", "str|null", "Set when query_enricher merged a follow-up"),
    ("decomposition", "dict", "intent, entities, geography, domains, time_*, africa_default, africa_panel"),
    ("measure_id", "str|null", "Resolved agri measure ontology id"),
    ("recency_tier", "str|null", "live | near_term | historical_ok | point_in_time"),
    ("task_mode", "str|null", "clarify|analytical|fact_lookup|briefing|data_export_only|research|chat"),
    ("analytical_mode", "bool|null", "True when task_mode == analytical"),
    ("bq_table_candidates", "list", "Staging YAML table hints from bq_reason"),
    ("bq_sql_plan", "dict", "selected_tables, query_intents, skip_bq, table_hints, measure_id"),
    ("vector_news_results", "list", "News corpus chunks (VECTOR LEG)"),
    ("vector_academic_papers_results", "list", "Academic papers chunks"),
    ("vector_policies_results", "list", "Policy document chunks"),
    ("vector_public_reports_results", "list", "Public report chunks"),
    ("vector_formation_results", "list", "Formation corpus chunks"),
    ("vector_ota_results", "list", "OTA insights chunks"),
    ("vector_academic_results", "list", "Deprecated alias (news+academic convenience)"),
    ("vector_results", "list", "Combined vector convenience list"),
    ("corpus_selection", "dict|null", "Corpus router output (selected keys, boosts)"),
    ("bq_results", "list", "Enriched BigQuery context items (BQ LEG)"),
    ("bq_sql_queries", "list", "Distinct SQL strings executed"),
    ("bq_sql_debug", "list", "Per-query debug metadata"),
    ("structured_ranking_cache", "dict|null", "Session-scoped ranking cache entry"),
    ("bq_cache_hit", "bool|null", "True when ranking follow-up reused cache"),
    ("merged_context", "list", "Vector + BQ (+ later web) before rerank"),
    ("reranked_context", "list", "Subset passed to generator"),
    ("web_results", "list", "Wikipedia/Tavily chunks from web_fallback"),
    ("web_fallback_status", "str|null", "ok | disabled | rate_limited | empty | error"),
    ("web_fallback_reason", "str|null", "Human-readable web fallback reason"),
    ("insufficient_context", "bool|null", "Route to gap answer after web failure"),
    ("answer", "str", "Final assistant prose"),
    ("citations", "list", "Structured citation objects"),
    ("usage", "dict", "LLM token totals"),
    ("error", "str|null", "Pipeline-level error string"),
    ("geo_override", "str|null", "API/UI geo override"),
    ("time_start_override", "str|null", "Retrieval date filter override"),
    ("time_end_override", "str|null", "Retrieval date filter override"),
    ("news_top_k", "int|null", "Max news chunks"),
    ("academic_top_k", "int|null", "Max academic chunks"),
    ("ota_top_k", "int|null", "Max OTA chunks"),
    ("bq_top_k", "int|null", "Max BQ rows/chunks"),
    ("rerank_top_k", "int|null", "Chunks after rerank"),
    ("conversation_summary", "str|null", "Rolling chat summary"),
    ("recent_turns", "list|null", "Last N verbatim Q/A pairs"),
    ("chat_history", "list|null", "Legacy client-owned history"),
    ("is_meta_query", "bool|null", "Route to generate_meta"),
    ("is_product_query", "bool|null", "Route to generate_product"),
    ("is_greeting_query", "bool|null", "Route to generate_social"),
    ("is_out_of_scope_query", "bool|null", "Route to generate_social"),
    ("is_language_unknown", "bool|null", "Route to generate_language_help"),
    ("plan_type", "str|null", "Free|Farmers|Government|NGOs|Agribusinesses|Integrated"),
    ("category", "str|null", "Generation persona"),
    ("user_profile", "dict|null", "country, plan_type, category"),
    ("acf_band", "str|null", "ACF confidence band"),
    ("acf_band_label", "str|null", "Human-readable band"),
    ("acf_score", "int|float|null", "0-100 composite score"),
    ("acf_explanation", "str|null", "One-sentence rationale"),
    ("acf_components", "dict|null", "Optional T/A/F/G breakdown"),
    ("answer_lang", "str|null", "Detected answer language tag"),
    ("session_id", "str|null", "Server session id"),
    ("export_enabled", "bool|null", "Allow artifact generation"),
    ("export_intent", "str|null", "csv|chart|docx|pdf|multi detected in query"),
    ("artifacts", "list", "Downloadable export descriptors"),
)

CORPUS_TABLE: Sequence[Sequence[str]] = (
    ("news", "news_data", "Timely journalism", "geo_country_primary, published_at, domains"),
    ("academic_papers", "academic_papers", "Peer-reviewed research", "country, publication_year"),
    ("policies", "policies", "Policy documents", "country, publication_year"),
    ("public_reports", "public_reports", "Institutional reports", "country, publication_year"),
    ("formation", "formation", "Training / farmer practice", "country, publication_year"),
    ("ota", "OTA_insights", "Analyst insights (triple vectors)", "country, insight lanes"),
)

LLM_MATRIX: Sequence[Sequence[str]] = (
    ("Decompose (optional)", "query_decomposer.py", "llm_chat", "Heuristics always; LLM enriches when configured"),
    ("BQ reasoner", "bq_sql_reasoner.py", "llm_chat", "Ontology-scoped; retries; ontology fallback last resort"),
    ("NL-to-SQL", "bq_retriever.py", "llm_chat", "Templates/patterns first when matched"),
    ("Rerank", "reranker.py", "cross_encoder default", "LLM rerank only when RAG_RERANKER_MODE=llm"),
    ("Generate", "generator.py", "llm_chat", "Vector+BQ context; persona/recency overlays"),
    ("Memory summary", "chat_memory.py", "llm_chat", "Text stub if no LLM"),
    ("Export prose", "export_runner.py", "llm_chat", "Optional report sections"),
)

ENV_VARS: Sequence[Sequence[str]] = (
    ("BQ_PROJECT", "BigQuery GCP project"),
    ("BQ_DATASET_SILVER", "Staging dataset for RAG SQL (default staging_dev)"),
    ("QDRANT_URL / QDRANT_API_KEY", "Vector database cluster"),
    ("QDRANT_COLLECTION_NEWS", "news_data override"),
    ("QDRANT_COLLECTION_ACADEMIC_PAPERS", "academic_papers override"),
    ("QDRANT_COLLECTION_POLICIES", "policies override"),
    ("QDRANT_COLLECTION_PUBLIC_REPORTS", "public_reports override"),
    ("QDRANT_COLLECTION_FORMATION", "formation override"),
    ("QDRANT_COLLECTION_OTA_INSIGHTS", "OTA_insights override"),
    ("RAG_CORPUS_ROUTER", "Heuristic gate over six corpora (on default)"),
    ("RAG_QDRANT_HYBRID_SEARCH", "Dense + BM25 sparse RRF fusion"),
    ("RAG_*_GEO_FALLBACK / RAG_*_TIME_FALLBACK", "Per-corpus cascade relax flags"),
    ("RAG_USE_LEGACY_RESEARCH_COLLECTION", "Optional legacy mixed research collection"),
    ("RAG_LLM_BASE_URL / RAG_LLM_API_KEY", "OpenAI-compatible LLM backend"),
    ("RAG_LLM_MODEL_ID", "Default generation model"),
    ("RAG_BQ_REASONER_MODEL_ID", "Dedicated BQ table-reasoner model"),
    ("RAG_BQ_REASONER_TIMEOUT_S", "Reasoner HTTP timeout override"),
    ("RAG_BQ_REASONER_RETRIES", "Reasoner retry count (default 3)"),
    ("RAG_BQ_NL2SQL_MODEL_ID", "Dedicated NL-to-SQL model"),
    ("RAG_RERANKER_MODE", "cross_encoder | openrouter | cohere | llm | off"),
    ("RAG_RERANKER_MODEL", "Cross-encoder model (default BAAI/bge-reranker-base)"),
    ("RAG_REDIS_URL", "Session blobs + shared caches"),
    ("RAG_SESSION_TTL_SECONDS", "Session TTL (default 86400)"),
    ("RAG_WEB_FALLBACK_ENABLED", "Post-rerank Wikipedia/Tavily (default off)"),
    ("RAG_CITATIONS_MODE", "referenced (default) or all"),
    ("RAG_GENERATE_MAX_TOKENS", "Answer length cap (default 2048)"),
    ("RAG_GENERATE_CONTEXT_MAX_CHARS", "Total context chars (default 12000)"),
    ("LANGFUSE_*", "Tracing and POST /feedback scores"),
)

VECTOR_RETRIEVAL_BULLETS: Sequence[str] = (
    "VECTOR LEG runs in parallel_retrieve BEFORE BQ reason/retrieve; both legs fuse at merge.",
    "Embeddings: fastembed (Railway) or sentence-transformers (local); E5 prefixes query: at search, passage: at index.",
    "Per corpus VectorRetriever: embed → payload filters (doc_kind, geo, time, news domains) → search.",
    "vector_search_mode: dense_named (single dense) or hybrid (dense + BM25 sparse RRF when RAG_QDRANT_HYBRID_SEARCH=on).",
    "Cascade (_retrieve_vector_cascade): full filters → time ±1 year → drop time → drop geo → drop both when env fallbacks allow.",
    "Surviving hits stamp constraint_relaxed when filters were widened; geo post-filter runs on all corpora after cascade.",
    "Soft-fail: empty corpus returns []; thread pool continues other corpora; graph never aborts on one empty collection.",
    "State writes: vector_news_results, vector_academic_papers_results, vector_policies_results, vector_public_reports_results, vector_formation_results, vector_ota_results, vector_results, corpus_selection.",
)

CORPUS_ROUTER_BULLETS: Sequence[str] = (
    "select_corpora (chatbot/corpus_catalog.py) chooses which of six collections to query.",
    "Inputs: query text, decomposition facets, plan_type, category, task_mode (briefing/research nudge news/academic).",
    "Heuristics + keyword/domain cues; stamps corpus_boost for merge/rerank.",
    "RAG_CORPUS_ROUTER=off restores fan-out to all six; never skips more than three corpora; never returns an empty set.",
    "Optional legacy mixed research collection only when RAG_USE_LEGACY_RESEARCH_COLLECTION=on.",
)

BQ_RETRIEVAL_BULLETS: Sequence[str] = (
    "BQ LEG is peer to vector — not a replacement for unstructured retrieval.",
    "agri_measure_ontology.resolve_measure scopes candidate tables and filter hints (Yield vs Production, trade, FEWS prices, IPC, soil, climate).",
    "reason_bq_sql_plan: ontology-scoped YAML index → LLM with retries → ontology fallback_plan last resort (not silent skip when measure known).",
    "Forced plans for analytical / fact_lookup / data_export_only from MeasureSpec (investor_best_country multi-table).",
    "Modes: RAG_BQ_NL2SQL_MODE=per_hint (default) or batch; templates + patterns (element=Yield when yield).",
    "Validation: bq_sql_validate — SELECT-only, staging_dev tables, LIMIT enforced.",
    "Row budget: RAG_BQ_ROWS_PER_QUERY per SQL, capped by bq_top_k total; enrich + ranking cache + trend companion.",
)

CONTROL_PLANE_BULLETS: Sequence[str] = (
    "query_enricher merges elliptical/anaphoric follow-ups with prior user turns before decompose.",
    "decompose_query + africa_default (which-country rank) or africa_panel (full ~54-country panel).",
    "resolve_measure → task_mode: clarify | analytical | data_export_only | fact_lookup | research | briefing | chat.",
    "needs_clarify is measure-aware (crop not required for IPC/soil/climate/GDP/investor_best_country).",
    "plan_policy preserves multi-geo when africa_default / africa_panel / expanded_regions (no Benin amputation).",
)

INGEST_ARCHITECTURE_BULLETS: Sequence[str] = (
    "Google Drive sync (ingestion/gdrive) or local files → text_processors/preprocess.",
    "JSONL under ml-eng/data/local/preprocessed_data/ (news, research, ota).",
    "Chunk IDs: UUID5 from chunking_config.CHUNK_ID_NAMESPACE.",
    "Loaders upsert to Qdrant; ingest_manifest.json tracks content_hash for incremental skip.",
    "Collection specs: scripts/qdrant_collection_specs.py (vectors, payload indexes).",
    "Rebuild: bump INGEST_VERSION or loader --reset after embedding/chunk changes.",
)

OBSERVABILITY_BULLETS: Sequence[str] = (
    "Langfuse: rag_trace_context wraps API/chat turns; observed_span per graph node.",
    "POST /feedback on RAG API records trace scores via langfuse_trace_id.",
    "include_trace on POST /query returns decomposition + retrieval counts.",
    "Streamlit inspector: full state, bq_sql_debug, bq_cache_hit, ACF fields.",
    "Redis keys: rag:session:<session_id> (TTL RAG_SESSION_TTL_SECONDS, default 24h).",
)

NODE_SPECS: list[dict[str, Any]] = [
    {
        "name": "decompose",
        "module": "chatbot/query_enricher.py, query_decomposer.py, agri_measure_ontology.py, task_mode.py, plan_policy.py",
        "purpose": "Enrich elliptical follow-ups, decompose facets, resolve measure/task_mode, classify route.",
        "reads": "query, conversation_summary, recent_turns, plan_type, category, user_profile",
        "writes": "query (if enriched), enriched_query, decomposition, measure_id, recency_tier, task_mode, analytical_mode, route flags, answer_lang, export_intent",
        "substeps": [
            "enrich_query_with_memory for anaphora / short follow-ups.",
            "decompose_query + africa_default or africa_panel annotation.",
            "expand_regions_in_decomposition for analytical/export/panel modes.",
            "apply_plan_decomposition_gates (preserve Africa panels).",
            "resolve_measure + resolve_task_mode (clarify / analytical / export / fact / research / briefing / chat).",
            "Detect meta, product, greeting, out-of-scope, unknown language.",
        ],
        "llm": "Optional (decomposer enrichment)",
        "external": "None",
        "failure": "Heuristics always succeed; LLM failure keeps heuristic decomposition.",
    },
    {
        "name": "parallel_retrieve",
        "module": "chatbot/graph.py, corpus_catalog.py, retrievers/vector_retriever.py, sparse_embeddings.py",
        "purpose": "VECTOR LEG — retrieve unstructured context from up to six Qdrant corpora in parallel.",
        "reads": "query, decomposition, corpus_selection inputs, geo/time overrides, top_k, plan_type, task_mode, category",
        "writes": "vector_*_results, vector_results, corpus_selection",
        "substeps": [
            "select_corpora: heuristic gate, max soft-skip 3, never empty, stamp corpus_boost.",
            "Thread pool: one VectorRetriever.retrieve per selected corpus.",
            "E5 embed with query: prefix; payload filters doc_kind/geo/time/domains.",
            "dense_named or hybrid (BM25 sparse + RRF) per collection profile.",
            "Cascade: full filters → time ±1y → drop time → drop geo; stamp constraint_relaxed.",
            "Geo post-filter; soft-fail empty corpora; continue graph.",
        ],
        "llm": "No",
        "external": "Qdrant Cloud",
        "failure": "Empty corpus returns []; graph continues.",
    },
    {
        "name": "bq_reason",
        "module": "chatbot/bq_sql_reasoner.py, agri_measure_ontology.py, bq_table_schema_yaml.py, fact_bq_plan.py, analytical_bq_plan.py",
        "purpose": "BQ LEG planner — ontology-scoped staging_dev table/SQL intents.",
        "reads": "query, decomposition, plan_type, category, task_mode, analytical_mode",
        "writes": "bq_sql_plan, bq_table_candidates",
        "substeps": [
            "resolve_measure + reasoner_scope; format_reasoner_index(table_ids=candidates).",
            "Forced analytical/fact/export plans from MeasureSpec when task_mode matches.",
            "Else LLM reasoner with retries; ontology fallback_plan or Africa heuristic last resort.",
            "Emit table_hints packs for NL2SQL.",
        ],
        "llm": "Yes (RAG_BQ_REASONER_MODEL_ID or default)",
        "external": "None",
        "failure": "Ontology/heuristic fallback when measure known; else skip_bq empty plan.",
    },
    {
        "name": "bq_retrieve",
        "module": "retrievers/bq_retriever.py, bq_context_enrich.py, bq_ranking_cache.py, bq_trend_companion.py",
        "purpose": "Execute BigQuery SQL and enrich rows into ACF-ready structured context.",
        "reads": "query, decomposition, bq_sql_plan, bq_table_candidates, structured_ranking_cache, bq_top_k, time overrides",
        "writes": "bq_results, bq_sql_queries, bq_sql_debug, structured_ranking_cache, bq_cache_hit",
        "substeps": [
            "Check ranking cache hit (list/export follow-up) — skip BQ if compatible.",
            "Template SQL fallback then NL2SQL per table hint.",
            "Validate SQL (SELECT-only, staging_dev allowlist, LIMIT).",
            "Execute against BigQuery; project_bq_row_acf on rows.",
            "enrich_bq_results: semantics prose, ranked_table consolidation.",
            "Stamp ACF metadata; FAOSTAT trend companion (Y-1 vs Y+1).",
            "trim_bq_result_contents; save ranking cache entry.",
        ],
        "llm": "Yes (NL2SQL; templates without LLM when matched)",
        "external": "BigQuery, optional Redis (schema cache)",
        "failure": "Diagnostic rows in bq_results; validation/execution errors in metadata.",
    },
    {
        "name": "merge",
        "module": "chatbot/graph.py",
        "purpose": "Combine BQ and vector chunks into unified merged_context with source labels.",
        "reads": "bq_results, vector_* lists, query",
        "writes": "merged_context",
        "substeps": [
            "Label BQ as [Structured data]; news/academic/policy/etc. with kind prefixes.",
            "Set _context_kind on each item (bigquery, news, academic, ...).",
            "Pin BQ first for ranking/numeric queries.",
            "Filter unusable diagnostic BQ rows.",
        ],
        "llm": "No",
        "external": "None",
        "failure": "Empty merge if all sources empty.",
    },
    {
        "name": "rerank",
        "module": "chatbot/reranker.py",
        "purpose": "Score and trim merged_context to reranked_context using cross-encoder or API rerankers.",
        "reads": "query, merged_context, decomposition, rerank_top_k",
        "writes": "reranked_context",
        "substeps": [
            "Select mode: cross_encoder, openrouter, cohere, llm, off.",
            "Apply static source boosts (BQ ranked_table, numeric/comparative queries).",
            "Min-max normalize scores; combine with boost.",
            "Trim to rerank_top_k (default 20).",
        ],
        "llm": "Only when RAG_RERANKER_MODE=llm",
        "external": "OpenRouter/Cohere APIs when configured",
        "failure": "Graceful degradation to cross_encoder then off.",
    },
    {
        "name": "web_fallback",
        "module": "retrievers/web_retriever.py",
        "purpose": "Append supplemental Wikipedia/Tavily chunks when internal context is thin.",
        "reads": "query, decomposition, reranked_context",
        "writes": "web_results, reranked_context (appended), web_fallback_status, web_fallback_reason, insufficient_context",
        "substeps": [
            "Trigger when usable chunks below RAG_WEB_FALLBACK_MIN_CHUNKS.",
            "Tier 1: Wikipedia shaped queries (no API key).",
            "Tier 2: Tavily if key set and daily limit not exceeded.",
            "Append web_wikipedia / web_search chunks to reranked_context.",
            "Set insufficient_context when web fails and context still thin.",
        ],
        "llm": "No",
        "external": "Wikipedia REST, Tavily API",
        "failure": "Fail-soft; may route to insufficient_context.",
    },
    {
        "name": "insufficient_context",
        "module": "chatbot/graph.py, answer_language.py",
        "purpose": "Return deterministic gap message without LLM hallucination.",
        "reads": "query, answer_lang",
        "writes": "answer, citations=[], acf=no_evidence",
        "substeps": [
            "Build localized insufficient_context_answer.",
            "Set ACF band no_evidence.",
        ],
        "llm": "No",
        "external": "None",
        "failure": "N/A (terminal node).",
    },
    {
        "name": "generate",
        "module": "chatbot/generator.py, acf_scoring.py, acf_metadata.py",
        "purpose": "Pack context, call LLM, extract citations, score ACF Path B on cited evidence.",
        "reads": "query, reranked_context, decomposition, conversation_summary, recent_turns, plan_type, category, answer_lang",
        "writes": "answer, citations, usage, acf_* fields, error",
        "substeps": [
            "Filter/drop geo-conflicting context when configured.",
            "Build numbered [Source N] context block with char budgets.",
            "Apply plan/category/structured-BQ prompt guards.",
            "LLM generate; strip preamble and invalid [N] markers.",
            "referenced_citations + score_cited_evidence.",
        ],
        "llm": "Yes (RAG_LLM_MODEL_ID / plan-specific model)",
        "external": "LLM provider",
        "failure": "Context-only fallback message; error string on pipeline failure.",
    },
    {
        "name": "export",
        "module": "chatbot/export_runner.py, chatbot/exports/*",
        "purpose": "Produce downloadable CSV/chart/DOCX/PDF when route enables exports and query requests them.",
        "reads": "export_enabled, export_intent, answer, citations, bq_results, reranked_context",
        "writes": "artifacts",
        "substeps": [
            "Skip if export_enabled false or no export_intent.",
            "run_exports: tabular rows from BQ/ranked_rows, chart PNG, docx/pdf builders.",
            "Upload to GCS or local URI; attach ArtifactItem list.",
        ],
        "llm": "Optional (report prose sections)",
        "external": "GCS (production), local filesystem (dev)",
        "failure": "Empty artifacts[]; answer still returned.",
    },
    {
        "name": "generate_meta",
        "module": "chatbot/assistant_identity.py",
        "purpose": "Answer identity/meta questions about Ask ADZA without retrieval.",
        "reads": "query, answer_lang",
        "writes": "answer, citations=[], curated ACF",
        "substeps": ["Return canned assistant identity response."],
        "llm": "No",
        "external": "None",
        "failure": "N/A (terminal).",
    },
    {
        "name": "generate_product",
        "module": "chatbot/product_knowledge.py",
        "purpose": "Answer product/how-to questions from curated knowledge.",
        "reads": "query",
        "writes": "answer, citations=[], curated ACF",
        "substeps": ["Match product FAQ patterns; no vector/BQ retrieval."],
        "llm": "No",
        "external": "None",
        "failure": "N/A (terminal).",
    },
    {
        "name": "generate_social",
        "module": "chatbot/query_gate.py",
        "purpose": "Handle greetings and out-of-scope queries politely.",
        "reads": "query, is_greeting_query, is_out_of_scope_query",
        "writes": "answer, citations=[]",
        "substeps": ["classify_social_query or generate_social_answer."],
        "llm": "No",
        "external": "None",
        "failure": "N/A (terminal).",
    },
    {
        "name": "generate_language_help",
        "module": "chatbot/answer_language.py",
        "purpose": "Ask user to rephrase when language cannot be detected.",
        "reads": "query, answer_lang",
        "writes": "answer, citations=[], curated ACF",
        "substeps": ["language_unclear_answer stub."],
        "llm": "No",
        "external": "None",
        "failure": "N/A (terminal).",
    },
]
