{{ config(materialized='table') }}

-- GBIF occurrences + ArcGIS rarity-80 birds richness/rarity layer.

select
    cast(gbif_id as string) as gbif_id,
    datasetKey as dataset_key,
    occurrenceID as occurrence_id,
    kingdom,
    phylum,
    class as classification,
    `order` as taxonomic_order,
    family,
    genus,
    species,
    infraspecificEpithet as infraspecific_epithet,
    taxonRank as taxon_rank,
    scientificName as scientific_name,
    verbatimScientificName as verbatim_scientific_name,
    countryCode as country_code,
    locality,
    stateProvince as state_province,
    occurrenceStatus as occurrence_status,
    individual_count,
    latitude,
    longitude,
    coordinate_uncertainty_m,
    elevation_m,
    year,
    month,
    day,
    eventDate as event_date,
    basisOfRecord as basis_of_record,
    taxon_key,
    species_key,
    ingested_at,
    cast(null as string) as feature_name,
    cast(null as float64) as area_km2,
    cast(null as float64) as prop_gadm,
    cast(null as int64) as rich_all,
    cast(null as int64) as rich_amph,
    cast(null as int64) as rich_bird,
    cast(null as int64) as rich_cact,
    cast(null as int64) as rich_coni,
    cast(null as int64) as rich_mamm,
    cast(null as int64) as rich_rept,
    cast(null as int64) as rar_all,
    cast(null as int64) as rar_amph,
    cast(null as int64) as rar_bird,
    cast(null as int64) as rar_cact,
    cast(null as int64) as rar_coni,
    cast(null as int64) as rar_mamm,
    cast(null as int64) as rar_rept,
    cast(null as float64) as area_protected,
    cast(null as string) as geometry_wkt,
    'gbif_biodiversity_occurrence' as source_natural_key,
    current_timestamp() as loaded_at
from {{ source('raw_dev', 'gbif_biodiversity_occurrence') }}

union all

select
    cast(objectid as string) as gbif_id,
    cast(null as string) as dataset_key,
    cast(null as string) as occurrence_id,
    cast(null as string) as kingdom,
    cast(null as string) as phylum,
    cast(null as string) as classification,
    cast(null as string) as taxonomic_order,
    cast(null as string) as family,
    cast(null as string) as genus,
    cast(null as string) as species,
    cast(null as string) as infraspecific_epithet,
    cast(null as string) as taxon_rank,
    cast(null as string) as scientific_name,
    cast(null as string) as verbatim_scientific_name,
    cast(null as string) as country_code,
    cast(null as string) as locality,
    cast(null as string) as state_province,
    cast(null as string) as occurrence_status,
    cast(null as int64) as individual_count,
    cast(null as float64) as latitude,
    cast(null as float64) as longitude,
    cast(null as float64) as coordinate_uncertainty_m,
    cast(null as float64) as elevation_m,
    cast(null as int64) as year,
    cast(null as int64) as month,
    cast(null as int64) as day,
    cast(null as string) as event_date,
    cast(null as string) as basis_of_record,
    cast(null as int64) as taxon_key,
    cast(null as int64) as species_key,
    cast(null as timestamp) as ingested_at,
    name as feature_name,
    area_km2,
    prop_gadm,
    rich_all,
    rich_amph,
    rich_bird,
    rich_cact,
    rich_coni,
    rich_mamm,
    rich_rept,
    rar_all,
    rar_amph,
    rar_bird,
    rar_cact,
    rar_coni,
    rar_mamm,
    rar_rept,
    analysisarea as area_protected,
    geometry_wkt,
    'arcgis_rarity_80_birds_africa' as source_natural_key,
    current_timestamp() as loaded_at
from {{ source('raw_dev', 'arcgis_rarity_80_birds_africa') }}
